version: '3.8'

services:
  web:
    build: .
    container_name: node_app
    ports:
      - "8080:3000"  # Expose port 3000 internally for the Node.js app
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - app_network

  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Map external port 8080 to Nginx's internal port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app_network

volumes:
  dbdata:

networks:
  app_network:
